import React, { useState } from 'react';
import { SendHorizontal } from 'lucide-react';

export default function ChatInput({ onSend, isTyping }) {
  const [text, setText] = useState('');

  const handleSend = () => {
    if (!text.trim()) return;
    onSend(text);
    setText('');
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="p-4 border-t border-white/[0.04] bg-[#0b0e14]/90 backdrop-blur-xl">
      <div className="relative flex items-center bg-[#151a26] border border-white/[0.08] rounded-xl focus-within:border-cyan-500/50 focus-within:ring-1 focus-within:ring-cyan-500/50 transition-all shadow-inner">
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask anything about your spending, budget, or anomalies..."
          className="w-full bg-transparent border-none text-white placeholder-gray-500 text-[14.5px] px-5 py-4 focus:ring-0 resize-none max-h-32 min-h-[56px] custom-scrollbar rounded-xl outline-none"
          rows={1}
          disabled={isTyping}
        />
        <button
          onClick={handleSend}
          disabled={!text.trim() || isTyping}
          className="absolute right-3 p-2 bg-gradient-to-r from-[#00f5a0] to-[#00d4ff] text-black rounded-lg disabled:opacity-30 disabled:grayscale transition-all hover:shadow-[0_0_15px_rgba(0,245,160,0.4)] active:scale-95"
        >
          <SendHorizontal className="w-5 h-5" />
        </button>
      </div>
      <div className="text-center mt-3 mb-1">
        <span className="text-[10px] text-gray-500 font-mono tracking-widest uppercase">Answers are generated by Llama 3.3. Verify important financial data.</span>
      </div>
    </div>
  );
}
